static int npc_collision_binding_check(void)
{
 campaign_npc_body owner={0};rf_entity_seeds saved=campaign_seeds;rf_level_owned_entity record={0};
 rf_entity_owned_pose owned={0};campaign_model_owner model={0};rf_entity_pose pose={0};rf_collision_pair_actor_state out,before;
 rf_movement_descriptor saved_mode=campaign_modes[3];uint32_t handle;
 campaign_npc_bodies=&owner;campaign_npc_body_count=1;campaign_seeds.records.items=&record;campaign_seeds.records.count=1;
 campaign_model_owners=&model;campaign_model_owner_count=1;
 rf_object_registry_init(&campaign_registry);memset(&campaign_entities,0,sizeof(campaign_entities));
 CHECK(rf_entity_view_register(&campaign_registry,&campaign_entities,&owner.view,&owner.registration)==RF_OK);handle=owner.registration.handle;
 owner.movement_slot=3;campaign_modes[3].index=8;owner.view.linked_handle=-1;
 {
  rf_geometry_collision_world world={0};rf_geometry_body_hit hit,before_hit;
  rf_physics_sphere sphere={0};rf_collision_body_sphere scratch;uint32_t matched=99;
  memset(&hit,0xa5,sizeof(hit));before_hit=hit;
  CHECK(rf_scene_npc_body_sweep(&world,handle^0x10000,&owner.body.state,0x460,&scratch,1,&hit,&matched)==RF_NOT_FOUND);
  CHECK(matched==99 && !memcmp(&hit,&before_hit,sizeof(hit)));
  CHECK(rf_scene_npc_body_sweep(NULL,handle,&owner.body.state,0x460,&scratch,1,&hit,&matched)==RF_RANGE);
  owner.body.spheres.items=&sphere;owner.body.spheres.count=1;
  CHECK(rf_scene_npc_body_sweep(&world,handle,&owner.body.state,0x460,&scratch,0,&hit,&matched)==RF_RANGE);
  CHECK(matched==99 && !memcmp(&hit,&before_hit,sizeof(hit)));
  CHECK(rf_scene_npc_body_sweep(&world,handle,&owner.body.state,0x460,&scratch,1,&hit,&matched)==RF_OK);
  CHECK(matched==0 && !memcmp(&hit,&before_hit,sizeof(hit)));
  owner.body.spheres.items=NULL;owner.body.spheres.count=0;
 }

 CHECK(rf_scene_collision_extra_velocity(NULL,handle)==owner.support_velocity);
 CHECK(!owner.support_velocity[0] && !owner.support_velocity[1] && !owner.support_velocity[2]);
 owner.support_velocity[0]=3;owner.support_velocity[1]=-7;owner.support_velocity[2]=11;
 CHECK(rf_scene_collision_extra_velocity(NULL,handle)[1]==-7);
 CHECK(!rf_scene_collision_extra_velocity(NULL,handle^0x10000));
 owner.view.type=2;CHECK(!rf_scene_collision_extra_velocity(NULL,handle));owner.view.type=0;
 owner.object_flags=0x12344000;owner.view.flags_7c=0;owner.body.state.flags=0x40000020;
 owner.published[0]=12;owner.published[1]=-5;owner.published[2]=9;
 record.record.orientation[2][0]=1;record.record.orientation[2][1]=2;record.record.orientation[2][2]=3;
 memset(&out,0xa5,sizeof(out));before=out;
 CHECK(rf_scene_npc_collision_view(handle^0x10000,&out)==RF_NOT_FOUND && !memcmp(&out,&before,sizeof(out)));
 CHECK(rf_scene_npc_collision_view(handle,NULL)==RF_RANGE);
 CHECK(rf_scene_npc_collision_view(handle,&out)==RF_OK);
 CHECK(out.kind==0 && out.body_flags==0x40000020 && out.model==0 && out.movement_mode==8);
 CHECK(out.handle==handle && out.parent_handle==UINT32_MAX && out.object_flags==0x12344000);
 CHECK(!out.trigger_filter && !out.allowed_count && !out.allowed_handles);
 CHECK(!memcmp(out.position,owner.published,12) && !memcmp(out.forward,record.record.orientation[2],12));
 model.registration.loaded=1;model.pose=&pose;model.registration.active=&pose.playback.completion.active;
 model.registration.next=model.registration.previous=&model.registration;
 CHECK(rf_scene_npc_collision_view(handle,&out)==RF_OK && out.model==1);
 model.owned=&owned;CHECK(rf_scene_npc_collision_view(handle,&out)==RF_OK && out.model==0);model.owned=0;
 owner.view.linked_handle=123;owner.published[1]=18;campaign_modes[3].index=1;owner.body.state.flags=0;
 CHECK(rf_scene_npc_collision_view(handle,&out)==RF_OK && out.parent_handle==123 && out.position[1]==18 && out.movement_mode==1 && out.body_flags==0);
 before=out;model.pose=NULL;
 CHECK(rf_scene_npc_collision_view(handle,&out)==RF_RANGE && !memcmp(&out,&before,sizeof(out)));model.pose=&pose;
 owner.movement_slot=16;CHECK(rf_scene_npc_collision_view(handle,&out)==RF_RANGE && !memcmp(&out,&before,sizeof(out)));owner.movement_slot=3;
 campaign_seeds.records.count=0;CHECK(rf_scene_npc_collision_view(handle,&out)==RF_RANGE && !memcmp(&out,&before,sizeof(out)));campaign_seeds.records.count=1;
 owner.view.type=2;CHECK(rf_scene_npc_collision_view(handle,&out)==RF_NOT_FOUND && !memcmp(&out,&before,sizeof(out)));owner.view.type=0;
 {
  rf_collision_actor_general_response response,untouched;rf_collision_actor_contact contact,readback;
  rf_physics_sphere spheres[2]={0};campaign_npc_body saved_owner,expected_owner;
  memset(&response,0xa5,sizeof(response));untouched=response;
  CHECK(rf_scene_npc_collision_response(handle,&response)==RF_RANGE && !memcmp(&response,&untouched,sizeof(response)));
  owner.body.allocated_bytes=sizeof(owner.body)+sizeof(spheres);owner.body.spheres.items=spheres;owner.body.spheres.count=2;
  owner.body.state.position[0]=111;owner.body.state.next_position[1]=222;owner.body.state.velocity[2]=333;
  owner.body.state.mass=7;owner.body.state.bounds.radius=4;owner.collision_material=3;
  owner.body.state.bounds.minimum[0]=-8;owner.body.state.bounds.maximum[2]=9;
  owner.body.state.orientation[1]=.5f;owner.body.state.next_orientation[7]=-.5f;
  memset(&contact,0x35,sizeof(contact));CHECK(rf_collision_contact_write(&owner.body.state,&owner.collision_contact,&contact)==RF_OK);
  saved_owner=owner;
  CHECK(rf_scene_npc_collision_response(handle,&response)==RF_OK && !memcmp(&owner,&saved_owner,sizeof(owner)));
  CHECK(response.actor.handle==handle && response.actor.material==3 && response.actor.spheres==spheres && response.actor.sphere_count==2);
  CHECK(response.actor.position[0]==111 && response.actor.next_position[1]==222 && response.actor.velocity[2]==333 && response.actor.mass==7);
  CHECK(response.actor.minimum[0]==-8 && response.actor.maximum[2]==9 && response.extent==4 && response.kind==0);
  CHECK(response.orientation[1]==.5f && response.next_orientation[7]==-.5f && !memcmp(&response.actor.contact,&contact,68));
  CHECK(response.actor.body_flags==owner.body.state.flags);
  memset(&contact,0x7f,sizeof(contact));expected_owner=owner;
  CHECK(rf_collision_contact_write(&expected_owner.body.state,&expected_owner.collision_contact,&contact)==RF_OK);
  expected_owner.body.state.flags=0x60000000;
  CHECK(rf_scene_npc_collision_publish(handle,0x60000000,&contact)==RF_OK && !memcmp(&owner,&expected_owner,sizeof(owner)));
  CHECK(rf_scene_npc_collision_response(handle,&response)==RF_OK && response.actor.body_flags==0x60000000 && !memcmp(&response.actor.contact,&contact,68));
  CHECK(rf_collision_contact_read(&owner.body.state,&owner.collision_contact,&readback)==RF_OK && !memcmp(&readback,&contact,68));
  saved_owner=owner;untouched=response;
  CHECK(rf_scene_npc_collision_publish(handle^0x10000,0,&contact)==RF_NOT_FOUND && !memcmp(&owner,&saved_owner,sizeof(owner)));
  CHECK(rf_scene_npc_collision_publish(handle,0,NULL)==RF_RANGE && !memcmp(&owner,&saved_owner,sizeof(owner)));
  CHECK(rf_scene_npc_collision_response(handle^0x10000,&response)==RF_NOT_FOUND && !memcmp(&response,&untouched,sizeof(response)));
  CHECK(rf_scene_npc_collision_response(handle,NULL)==RF_RANGE);
  owner.body.spheres.items=NULL;
  CHECK(rf_scene_npc_collision_response(handle,&response)==RF_RANGE && !memcmp(&response,&untouched,sizeof(response)));
  owner.body.spheres.items=spheres;owner.body.spheres.count=0x80000000u;
  CHECK(rf_scene_npc_collision_response(handle,&response)==RF_RANGE && !memcmp(&response,&untouched,sizeof(response)));
  owner.body.spheres.count=0;owner.body.spheres.items=NULL;
  CHECK(rf_scene_npc_collision_response(handle,&response)==RF_OK && !response.actor.sphere_count && !response.actor.spheres);
 }
 CHECK(rf_entity_view_unregister(&campaign_registry,&campaign_entities,&owner.registration)==RF_OK);
 CHECK(!rf_scene_collision_extra_velocity(NULL,handle));
 CHECK(rf_scene_npc_collision_view(handle,&out)==RF_NOT_FOUND && !memcmp(&out,&before,sizeof(out)));
 campaign_seeds=saved;campaign_modes[3]=saved_mode;campaign_npc_bodies=NULL;campaign_npc_body_count=0;
 campaign_model_owners=NULL;campaign_model_owner_count=0;return 0;
}
