"""Independent small rectangular Morton-layout controls for memory readback."""
from pathlib import Path
import sys
import struct
import unittest
sys.path.insert(0,str(Path(__file__).resolve().parents[1]/'tools'))
from xemu_texture_audit import swizzle_rgba, compare_atlas


class TextureAuditTests(unittest.TestCase):
    def test_packed_chart_offsets_and_corruption(self):
        # Hand-authored Morton order, not generated by the audit's address helper.
        actual = struct.pack('<8H', *[0x8000+i for i in [0,1,4,5,2,3,6,7]])
        row = dict(map='3', atlas_x='2', atlas_y='0', width='2', height='2',
                   packed=struct.pack('<4H',0x8002,0x8003,0x8006,0x8007).hex())
        self.assertEqual(compare_atlas(actual,4,2,[row]),4)
        damaged = bytearray(actual)
        damaged[8] ^= 1
        with self.assertRaisesRegex(ValueError, 'texel differs'):
            compare_atlas(damaged,4,2,[row])
        # Outside chart ownership is intentionally not compared.
        damaged = bytearray(actual)
        damaged[0] ^= 1
        self.assertEqual(compare_atlas(damaged,4,2,[row]),4)
        for rows in ([], [row,row], [dict(row,atlas_x='3')], [dict(row,packed='00')]):
            with self.assertRaises(ValueError):
                compare_atlas(actual,4,2,rows)
        with self.assertRaises(ValueError):
            compare_atlas(actual[:-1],4,2,[row])

    def test_rectangular_layouts(self):
        raw = b''.join(bytes([i])*4 for i in range(8))
        self.assertEqual(swizzle_rgba(raw,4,2),
                         b''.join(bytes([i])*4 for i in [0,1,4,5,2,3,6,7]))
        self.assertEqual(swizzle_rgba(raw,2,4),raw)

    def test_invalid_dimensions_and_size(self):
        for width,height,data in [(3,2,bytes(24)),(4,2,bytes(31)),(0,2,b'')]:
            with self.assertRaises(ValueError):
                swizzle_rgba(data,width,height)


if __name__ == '__main__':
    unittest.main()
