"""Paired reset save/reload followed by a real rocket, with uninterrupted control.

Requires inputs generated by check_paired_authored_reset.py. No HDD images or
host input are used; all replay commands stay inside rf_pc_play.
"""
import json
import os
from pathlib import Path
import struct
import subprocess

ROOT = Path(__file__).resolve().parents[1]
folder = ROOT / 'artifacts/paired-reset-checkpoint'
folder.mkdir(parents=True, exist_ok=True)
reset = (ROOT / 'artifacts/paired-reset/reset.bin').read_bytes()
recut = (ROOT / 'artifacts/paired-reset/recut.bin').read_bytes()
assert reset[:8] == b'RFI6' + struct.pack('<I', 48)
assert len(reset) == 8 + 850 * 48 and len(recut) == 8 + 1150 * 48
assert recut[:len(reset)] == reset
# The reset run executes records 1..849. Resume record 0 is initialization;
# its records 1..300 reproduce uninterrupted records 850..1149.
resume = reset[:8] + bytes(48) + recut[len(reset):]
env = {k: v for k, v in os.environ.items()
       if not k.startswith(('RF_REPLAY_', 'RF_DEV_'))}
env.update(RF_REPLAY_LEVEL='ctf06.rfl', RF_REPLAY_ARCHIVE='levelsm.vpp',
           RF_REPLAY_DEV_ROOM='1', RF_REPLAY_AUTHORED_SOURCES='2',
           RF_REPLAY_PLAYER_CHECKPOINT='1')


def run(name, payload, load=None):
    inputs = folder / (name + '.bin')
    inputs.write_bytes(payload)
    output = folder / (name + '.rfcp')
    output.unlink(missing_ok=True)
    local = dict(env, RF_REPLAY_GEOMOD_CHECKPOINT_OUT=str(output))
    if load is not None:
        local['RF_REPLAY_GEOMOD_CHECKPOINT_IN'] = str(load)
    with (folder / (name + '.log')).open('wb') as log:
        result = subprocess.run([
            str(ROOT / 'build/pc/Release/rf_pc_play.exe'), '--spawn-replay',
            str(ROOT / 'Installed_Game'), str(inputs), str(folder / (name + '.ppm')),
        ], cwd=ROOT, env=local, stdout=log, stderr=subprocess.STDOUT, timeout=180)
    assert result.returncode == 0 and output.exists(), f'Inspect {name}.log'
    data = output.read_bytes()
    assert data[:4] == b'RFCP' and struct.unpack_from('<I', data, 16)[0] == 3
    assert data[576:580] == b'RFDS' and struct.unpack_from('<I', data, 580)[0] == 3
    lines = (folder / (name + '.log')).read_text(encoding='utf-8').splitlines()
    def last(label):
        return list(map(int, [l for l in lines if l.startswith(label + ' ')][-1].split()[1:]))
    return data, {k: last(k) for k in ('AUTHORED_SOURCE_CUTS', 'TERRAIN_PUBLICATION', 'DETACHED_PIECES')}


saved, initial = run('save', reset)
assert initial['AUTHORED_SOURCE_CUTS'] == [94, 0, 93, 0, 0, 0, 0, 0]
assert initial['TERRAIN_PUBLICATION'][2:4] == [0, 3]
assert initial['DETACHED_PIECES'][1:3] == [0, 0]
resumed, final = run('resume', resume, folder / 'save.rfcp')
control, expected = run('control', recut)
assert final['AUTHORED_SOURCE_CUTS'] == [94, 0, 93, 1, 0, 0, 0, 0]
assert final['TERRAIN_PUBLICATION'][2:4] == [1, 4]
assert final['DETACHED_PIECES'][1:3] == [1, 1]
assert resumed == control, 'Reset-save continuation differs'
for label in final:
    # Publication peak measures process history: the control also performed
    # the two pre-reset cuts. Compare live state, not that high-water mark.
    indices = (0, 1, 2, 3, 4, 6, 7) if label == 'TERRAIN_PUBLICATION' else range(len(final[label]))
    assert all(final[label][i] == expected[label][i] for i in indices), label
report = dict(result='PASS', save_bytes=len(saved), continuation_bytes=len(resumed),
              reset=initial, recut=final,
              scope='PC paired reset save/reload and subsequent real rocket match uninterrupted composed state exactly; native coverage is separate.')
(folder / 'report.json').write_text(json.dumps(report, indent=2) + '\n', encoding='utf-8')
print(json.dumps(report, indent=2))
