"""Execute original48f62f..48f64a gravity arithmetic, no service replacements."""
from probe_debris_motion import ROOT,hashlib,json,struct,pefile,Uc,UC_ARCH_X86,UC_MODE_32
from unicorn.x86_const import UC_X86_REG_ESI,UC_X86_REG_ESP,UC_X86_REG_EIP,UC_X86_REG_FPCW
import itertools

def main():
    raw=(ROOT/'Installed_Game/RF.exe').read_bytes()
    sha=hashlib.sha256(raw).hexdigest()
    assert sha=='b8fb9ab4c9bfc6f2868c30839d6cfc69f84b8c25d7e54eee1325f5b633c9b836'
    image=pefile.PE(data=raw).get_memory_mapped_image()
    u=Uc(UC_ARCH_X86,UC_MODE_32);u.mem_map(0x400000,(len(image)+4095)&~4095);u.mem_write(0x400000,image)
    arena=0x30000000;u.mem_map(arena,65536)
    rows=[]
    for velocity,gravity,dt in itertools.product([-100,-1.7,-.16333334,0,.16333334,3.25,100],[0,1,9.8,30,-9.8],[0,1/60,.125,.25]):
        data=struct.pack('<3f',velocity,gravity,dt)
        u.mem_write(arena+0x4c,data[:4]);u.mem_write(0x5a00dc,data[4:8]);u.mem_write(0x5a4014,data[8:])
        u.reg_write(UC_X86_REG_ESI,arena);u.reg_write(UC_X86_REG_ESP,arena+0xe000);u.reg_write(UC_X86_REG_FPCW,0x27f)
        u.emu_start(0x48f62f,0x48f64a,count=100)
        assert u.reg_read(UC_X86_REG_EIP)==0x48f64a
        rows.append(dict(inputs=list(struct.unpack('<3I',data)),output=struct.unpack('<I',u.mem_read(arena+0x4c,4))[0]))
    folder=ROOT/'artifacts/debris-motion';folder.mkdir(exist_ok=True)
    (folder/'gravity-original.json').write_text(json.dumps(dict(original_sha256=sha,cases=rows,scope='Gravity arithmetic only, no collision/rotation/actor damage execution.'),indent=2)+'\n')
    (ROOT/'tests/fixtures/debris_gravity.inc').write_text('/* Original48f62f..48f64a; generated by tools/probe_debris_gravity.py. */\n'+''.join(' {{'+','.join(str(x)+'u' for x in r['inputs'])+'},'+str(r['output'])+'u},\n' for r in rows))
    print('PASS captured',len(rows),'original gravity results')

if __name__=='__main__':main()
