"""Execute original pre-collision debris motion and emit exact C fixtures."""
import hashlib
import itertools
import json
from pathlib import Path
import struct
import sys
ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT/'local/python'))
import pefile
from unicorn import Uc,UC_ARCH_X86,UC_MODE_32,UC_HOOK_CODE
from unicorn.x86_const import UC_X86_REG_ESP,UC_X86_REG_EIP,UC_X86_REG_FPCW

def main():
    original=ROOT/'Installed_Game/RF.exe';sha=hashlib.sha256(original.read_bytes()).hexdigest()
    assert sha=='b8fb9ab4c9bfc6f2868c30839d6cfc69f84b8c25d7e54eee1325f5b633c9b836'
    pe=pefile.PE(str(original));image=pe.get_memory_mapped_image();base=pe.OPTIONAL_HEADER.ImageBase
    u=Uc(UC_ARCH_X86,UC_MODE_32);u.mem_map(base,(len(image)+4095)&~4095);u.mem_write(base,image)
    arena=0x30000000;u.mem_map(arena,65536);room=arena+0x1000;chunk=arena+0x2000;stack=arena+0xe000
    f=lambda *x:struct.pack('<'+'f'*len(x),*x)
    w=lambda *x:struct.pack('<'+'I'*len(x),*x)
    words=lambda b:list(struct.unpack('<'+'I'*(len(b)//4),b))
    def stop(cpu,address,size,context):
        if address==0x48f990:cpu.emu_stop()
    u.hook_add(UC_HOOK_CODE,stop);rows=[]
    for flag,y,dt,velocity in itertools.product([0,1,2,255],[-1.0000001192092896,-1,-.9999999403953552],
                                               [0,1/60,.25],[(2,3,4),(-7.3,-1.7,11.1)]):
        start=(1.25,y,-3.75);depth=.25;bottom=-1.25
        u.mem_write(room,bytes(512));u.mem_write(room+0x184,w(flag));u.mem_write(room+0x188,f(depth));u.mem_write(room+12,f(bottom))
        u.mem_write(chunk,bytes(256));u.mem_write(chunk+8,f(*start));u.mem_write(chunk+0x48,f(*velocity));u.mem_write(chunk+0x6c,w(room))
        u.mem_write(0x6460e8,w(arena+0x3000));u.mem_write(0x5a4014,f(dt));u.mem_write(stack,w(arena+0xff00,chunk))
        u.reg_write(UC_X86_REG_ESP,stack);u.reg_write(UC_X86_REG_FPCW,0x27f)
        u.emu_start(0x48f900,arena+0xff00,count=10000);assert u.reg_read(UC_X86_REG_EIP)==0x48f990
        output=words(bytes(u.mem_read(u.reg_read(UC_X86_REG_ESP)+0x24,12)))
        rows.append(dict(flag=flag,inputs=words(f(*start,*velocity,dt,depth,bottom)),output=output))
    folder=ROOT/'artifacts/debris-motion';folder.mkdir(exist_ok=True)
    (folder/'original.json').write_text(json.dumps(dict(original_sha256=sha,cases=rows,
        scope='Original48f900 through48f990, real4ce080 and vector helpers; stops before collision, no substituted services.'),indent=2)+'\n')
    target=ROOT/'tests/fixtures/debris_motion.inc';target.parent.mkdir(exist_ok=True)
    target.write_text('/* Generated by tools/probe_debris_motion.py; original executable hash checked. */\n'+
        '\n'.join(' {'+str(r['flag'])+', {'+','.join(str(x)+'u' for x in r['inputs'])+'}, {'+
                    ','.join(str(x)+'u' for x in r['output'])+'}},' for r in rows)+'\n')
    print('Captured',len(rows),'original motion cases with inclusive water boundary and exact float words')

if __name__=='__main__':main()
