struct Input { float3 position : POSITION; float3 color : DIFFUSE; float3 texture : TEXCOORD0; float3 lightmap : TEXCOORD1; };
struct Output { float4 position : POSITION; float4 color : COLOR; float4 texture : TEXCOORD0; float4 lightmap : TEXCOORD1; };
Output main(Input input) {
    Output output;
    output.position = float4(input.position, 1.0);
    output.color = float4(input.color, 1.0);
    output.texture = float4(input.texture.xy, 0.0, input.texture.z);
    output.lightmap = float4(input.lightmap.xy, 0.0, input.lightmap.z);
    return output;
}
